### ISSUE TITLE
Error right after installation completes

### ISSUE THREAD

**Issue by FernandoTBarros** [onlyfang/VBoxVmService#10]
Hi! Please help me,
I'm having this error on a Windows Server Enterprise 2007 right after the installation completes:
![image](https://user-images.githubusercontent.com/3437672/50965723-f1d0a980-14b9-11e9-8881-9de6d49e56c1.png)
![image](https://user-images.githubusercontent.com/3437672/50965751-0c0a8780-14ba-11e9-9ac9-148ba61a783e.png)

If I try to execute VmServiceTray.exe:
![image](https://user-images.githubusercontent.com/3437672/50965788-293f5600-14ba-11e9-9a07-f1e8640bf23a.png)

**Comment by onlyfang** [comment]
Do you mean Windows Server 2008? I don't understand the language, but it looks like something about invalid Win32 executable. If I guess correctly it's because the binary is now built with cmake without enabling v120_xp toolset. Without this the binary is not compatible on some old systems like XP/2003, and maybe 2008, too.

Since those systems are really too old, I'll not try to provider compatibility for them any longer. But if you have to stay at it, you can try to compile by yourself. Just install Visual Studio 2013 and provider an additional option `-DCMAKE_GENERATOR_TOOLSET=v120_xp` to cmake comand line in do_build.bat. Good luck!
