### ISSUE TITLE
Windows Defender detected virus.

### ISSUE THREAD

**Issue by buchpat** [onlyfang/VBoxVmService#43]
Hi,

My installation got detected as a trojana.

![grafik](https://user-images.githubusercontent.com/28731736/76697119-2ed29600-6693-11ea-8b4c-ccfc377acb06.png)

![grafik](https://user-images.githubusercontent.com/28731736/76697096-e74c0a00-6692-11ea-90de-87a625c31063.png)

**Comment by onlyfang** [comment]
The install package will install VmServiceTray to Start Menu and Desktop, so that you can click to run it when you want, but it **will not** install VmServiceTray to Startup folder. I just downloaded the setup I posted at the Release page to double check. Did you add the second lnk after installation?

**Comment by buchpat** [comment]
That can be.
I also found an articel the this tool is used for cryptomining.

https://cybersafe.mcttrainingconsultant.com/itsecurity/loudminer-cross-platform-mining-in-cracked-vst-software/


thanks

**Comment by clau-bucur** [comment]
I have also got the same threat warning.
It tried to install the VmServiceTray to Startup folder also.
Is the setup compromised?

![image](https://user-images.githubusercontent.com/47672949/78395028-5fa04e00-75f5-11ea-9d6c-bbd5fc112a55.png)

**Comment by davide-trellis** [comment]
FWIW, I got this too, but it's not in startup:
![image](https://user-images.githubusercontent.com/39810699/78414650-0672f300-75d2-11ea-86e4-732a12c6ff39.png)

**Comment by onlyfang** [comment]
Strange enought I didn't see this warning with Windows Defender turned on on my Windows 10. 

@buchpat Your messge seems to indicate this is caused by cracked version of Visual Studio. Just to clarify I am using Visual Studio Community 2019.

I am still confident what I posted out in release section is clean. Since this is a opensouce project people in doubt please try to compile the exe from source on your own by runing "do_build.bat".
