### ISSUE TITLE
VmServiceControl.exe trojan

### ISSUE THREAD

**Issue by mariusebastian** [onlyfang/VBoxVmService#47]
The in the Kiwi release the file "VmServiceControl.exe" tests positive for trojan/Zpevdo.a

**Comment by onlyfang** [comment]
I tried to re-pack the setup file with a newer version of InnoSetup. Please check if it is still reported false positive.

**Comment by rohanc** [comment]
I noticed this today too.

Is there somewhere I can download the newest version so I can test it? I haven't got Visual Studio loaded so I can't build it myself.

![detection](https://user-images.githubusercontent.com/1295900/82138649-97d1b800-9854-11ea-985f-bf9323e351cd.png)

Attached are the results from virustotal.com

**Comment by onlyfang** [comment]
@rohanc https://github.com/onlyfang/VBoxVmService/releases/download/6.1-Kiwi/VBoxVmService-6.1-Kiwi.exe

**Comment by rohanc** [comment]
Windows Defender still flags the new 6.1-Kiwi.exe as a threat with this output:

Threat detected: Trojan:Win32/Wacatac.C!ml
Altert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

**Comment by onlyfang** [comment]
I am sorry there is no easy fix.

According to post in [Inno Setup forum ](https://groups.google.com/forum/#!searchin/innosetup/malware|sort:date/innosetup/w2weZ4afFqs/S62Rm5dfAgAJ), this is most likely because some virus and malware authors also use InnoSetup, and that some antivirus/malware software detect the presence of the installer instead of the bad payload.

I don't have too much time to deal with all the antivirus vendors. I'll close the ticket. People in double should just find a way to compile the executable by their own.

**Comment by rohanc** [comment]
That's fair enough. I understand you only have limited time to work on this project. 

Hopefully we as a user community can figure this one out or otherwise I fear this will drastically shrink the number of people able to utilise your excellent work.

I was first made aware of the problem when VmServiceTray.exe was flagged as malware. Does that contain Inno Setup too?

If it's only Inno Setup, is there a way that VBoxVmService could be distributed without an installer?

**Comment by mariusebastian** [comment]
In my case it was detected by Windows defender, so even if you don't want to deal with "all of the anti virus vendors" you might want to get your Windows app accepted by Windows....

**Comment by onlyfang** [comment]
@mariusebastian I've just submited the setup file for malware alanyze to https://www.microsoft.com/en-us/wdsi/filesubmission/. Hopefully that can help to clear the flag.

**Comment by onlyfang** [comment]
Just to update that Microsoft has processed my request, and removed detection from Windows defender.
