### ISSUE TITLE
VirusTotal: 14 detections as of 2020-08-15 for VBoxVmService-6.1-Kiwi.exe

### ISSUE THREAD

**Issue by 2072** [onlyfang/VBoxVmService#50]
Hello,

I'm not sure if you are aware of it but the latest release (VBoxVmService-6.1-Kiwi.exe) is detected by 14 anti-virus on VirusTotal.com

https://www.virustotal.com/gui/file/6e1f8272e693e0974176873952242d36252f537dcea024596bad7d68ae51275f/detection

**Comment by onlyfang** [comment]
According to [post in Inno Setup forum](https://groups.google.com/forum/#!searchin/innosetup/malware%7Csort:date/innosetup/w2weZ4afFqs/S62Rm5dfAgAJ) , this is most likely because some virus and malware authors also use InnoSetup, and that some antivirus/malware software detect the presence of the installer instead of the bad payload.

It was also flagged as Trojan by Windows defender back to May, but then cleared after I submited the setup file to Microsoft for malware alanyze.

I'll close the ticket. People in double should just find a way to compile the executable by their own.
