### ISSUE TITLE
Can't start vm without first rebooting

### ISSUE THREAD

**Issue by usjpaq** [onlyfang/VBoxVmService#53]
We have an install process that mainly consists of:

1. Install Virtualbox
2. set VBOX_USER_HOME
3. install VBoxVMService
4. Import OVF
5. configure folder sharing with VBoxManage
6. Update VBoxVmService.ini with new VM
7. Start the service with `VmServiceControl.exe -s`

Unfortunately the VM doesn't start and the following command line operations do not enumerate or start the vm:

`VmServiceControl.exe -l` 

```
Failed to list all virtual machines.
Error finding machine! Could not find a registered machine named 'scpedge'
```

`VmServiceControl.exe -su 0`

```
Failed to start up virtual machine.
Error finding machine! Could not find a registered machine named 'scpedge'
```

```
C:\vms>VmServiceControl.exe -k
Service stopped successfully

C:\vms>VmServiceControl.exe -u
Service VBoxVmService removed

<2 minute wait>

C:\vms>VmServiceControl.exe -i
Service VBoxVmService installed

C:\vms>VmServiceControl.exe -s
Service started successfully

C:\vms>VmServiceControl.exe -l
Failed to list all virtual machines.
Error finding machine! Could not find a registered machine named 'scpedge'
```

After rebooting the vm autostarts and the above commands work fine. Should we be doing something in a different order so that the system works prior to rebooting?

**Comment by onlyfang** [comment]
You are expected to setup VBOX_USER_HOME inside VBoxVmService.ini. And since VBoxVmService service is installed by the setup program before you got a chance to update VBoxVmService.ini, a reboot is probably required before your change to VBOX_USER_HOME takes effects. 

But if your VBOX_USER_HOME is the default place, that is, the .VirtualBox folder under your user HOME folder, you don't need to change anything and it is expected to work right after installation.

**Comment by usjpaq** [comment]
I dug into this issue a bit more and found that no matter how VBOX_USER_HOME is set, VboxSVC won't see it unless the system is rebooted first (so that dcomlaunch can see the new environment variable)
